### PR TITLE
Configuring for pure-python

### PR DESCRIPTION
**Pull request by icemac**
First attempt. Locally the shpinx doctests break for all Python versions. In GHA only the Python 2 bases ones seem to have a problem.

### CODE REVIEW

**Comment by icemac** [comment]
@jamadden Do you have an idea what causes these errors? Could it be because there is no final release of `zope.interface 5.3`?

**Comment by jamadden** [comment]
I suppose it's possible? I can't reproduce it locally after trying a couple different ways. What happens if you add `PIP_UPGRADE_STRATEGY: eager` to the environment variables?

**Comment by dataflake** [comment]
Seeing the same error locally. `PIP_UPGRADE_STRATEGY` doesn't help.

@jamadden What was the reason again to release `zope.interface` as alpha? Is there too much risk for breakage?

```
Installing test.
Version and requirements information containing zope.interface:
  Requirement of zope.testrunner: zope.interface
  Requirement of zope.catalog[test]: zope.interface
  Requirement of zope.interface: setuptools
  Requirement of zope.exceptions: zope.interface
  Requirement of zope.site: zope.interface>=4.5.0
  Requirement of zope.schema: zope.interface>=5.0.0
  Requirement of zope.location: zope.interface>=4.0.2
  Requirement of zope.lifecycleevent: zope.interface
  Requirement of zope.index>=3.5.0: zope.interface
  Requirement of zope.container: zope.interface
  Requirement of zope.component>=3.8: zope.interface>=5.3.0a1
  Requirement of zope.intid: zope.interface
  Requirement of zope.annotation: zope.interface
  Requirement of BTrees: zope.interface
  Requirement of persistent: zope.interface
  Requirement of zope.security: zope.interface
  Requirement of zope.interface>=4.5.0: setuptools
  Requirement of zope.component>=4.5.0: zope.interface>=5.3.0a1
  Requirement of zope.interface>=5.0.0: setuptools
  Requirement of zope.schema>=4.2.2: zope.interface>=5.0.0
  Requirement of zope.proxy>=4.0.1: zope.interface
  Requirement of zope.interface>=4.0.2: setuptools
  Requirement of BTrees>=4.4.1: zope.interface
  Requirement of zope.traversing>=4.0.0a1: zope.interface>=4.0.4
  Requirement of zope.size: zope.interface
  Requirement of zope.publisher: zope.interface>=4.0.1
  Requirement of zope.proxy>=4.1.5: zope.interface
  Requirement of zope.location>=3.5.4: zope.interface>=4.0.2
  Requirement of zope.lifecycleevent>=3.5.2: zope.interface
  Requirement of zope.filerepresentation: zope.interface
  Requirement of zope.component: zope.interface>=5.3.0a1
  Requirement of persistent>=4.1.0: zope.interface
While:
  Installing test.
Error: There is a version conflict.
We already have: zope.interface 5.2.0
but zope.component 5.0.0 requires 'zope.interface>=5.3.0a1'
```

**Comment by jamadden** [comment]
> What was the reason again to release zope.interface as alpha? Is there too much risk for breakage?

There was some risk, but the main reason was to get an answer to https://github.com/zopefoundation/zope.interface/issues/236: We've changed a `__repr__` in a way that could break doctests, we're considering changing others, and it would be good not to have to change doctests twice.

**Comment by dataflake** [comment]
This buildout failure will hit every single buildout that doesn't pin the version for zope.component. IMHO that's a bigger problem than having to change doctests. If the decision was up to me I'd release zope.interface ASAP.

**Comment by jamadden** [comment]
Since none of the zopetoolkit packages had any issues with the changed repr, my concern about having to change doctests twice is lessened, but I haven't tried to test any higher level packages. I have no problem with making a final release, but I can't today, I'm away from the computer with family for my youngest niece's birthday. If someone else wanted to, that's fine with me.

**Comment by dataflake** [comment]
@jamadden Have fun!

@icemac Looks like the GitHub actions created and uploaded all wheels and only the sdist is missing. I am not a `zope.interface` maintainer but you are. Could you make me maintainer or create/upload the sdist from the 5.3.0 tag? Thanks!

**Comment by jamadden** [comment]
Uploaded. Thank you.

**Comment by icemac** [comment]
@dataflake I've sent you an invitation on PyPI.

**Comment by icemac** [comment]
It seems that the final release of `zope.interface` actually helped to fix the tests. I am now going to work un the linting errors.

**Review by jamadden — APPROVED** [review]
Seems fine to me.

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
